name: me-drugban
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy>=1.20
  - pandas>=1.2
  - scikit-learn>=0.24
  - yacs=0.1.8
  - prettytable>=2.2.1
  - rdkit=2021.03.2
  # PyTorch build for CUDA 11.3
  - pytorch=1.10.2
  - torchvision=0.11.3
  - torchaudio=0.10.2
  - cudatoolkit=11.3
  # DGL GPU build for CUDA 11.3
  - dgl-cuda11.3=0.7.1
  - pip:
      - dgllife==0.2.8
      - comet-ml==3.23.1
      - tqdm